apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: microservices-ci-cd-order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: PRODUCT_SERVICE_URL

            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: APP_ENV

            - name: LOGGING_PATTERN_CONSOLE
              value: "%d{HH:mm:ss} %-5level [%X{correlationId}] %logger{36} - %msg%n"